### PR TITLE
Support Description field in corresponding entities

### PR DESCRIPTION
**Pull request by alvarolopez**
The Description field should be supported across all entities, as it is
included in the "Shared Entity Schema".

Fixes: #548

### CODE REVIEW

**Comment by mrutkows** [comment]
@alvarolopez I believe we held off placing support for it in the client since the Description is not yet recognized or stored at the server.  This would have to be done by using the object's metadata field (to not alter server schema) and corresponding changes to the Client / CLI to allow them to be read/written as well.

**Comment by alvarolopez** [comment]
@mrutkows I believe that adding the description field worked for me, I need to check and keep you posted, as I remember some fields not working as you say.

**Comment by mrutkows** [comment]
@alvarolopez I will merge this change allowing the "Description" to be part of the schema, but to be clear, any description data will not be respected at the server (i.e., not stored directly or in Annotation metadata) without further changes in wskdeploy to read/write this info. to the Annotations (OR get the server-side schema to allow Description to be a key on the actual Rule, Trigger, etc. entities directly).

**Comment by alvarolopez** [comment]
@mrutkows I forgot to reply to you: we're fine with not storing the description at server-side, but having it as part of the schema so that every action can include a description. Many thanks.

**Pull request merged**
